//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Email { get; set; }
        public byte[] Contrasena { get; set; }
    }
}
